version: "3.3"

volumes:
  redis-data: null
  postgres-data: null
  gem_cache: null
  exclude: null

networks:
  mars-images-network:

services:
  redis:
    image: redis
    command: redis-server --requirepass password
    ports:
      - 6379:6379
    volumes:
      - "redis-data:/data"
    networks:
      - mars-images-network

  postgresql:
    image: postgres:10
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    networks:
      - mars-images-network

  webpack:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ./bin/webpack-dev-server
    ports:
      - "3035:3035"
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    volumes:
      - ./:/opt/app
      - exclude:/opt/app/node_modules
      - gem_cache:/usr/local/bundle/gems
    networks:
      - mars-images-network
      
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpack
    depends_on:
      - postgresql
      - redis
      - webpack
    volumes:
      - ./:/opt/app
      - exclude:/opt/app/node_modules
      - gem_cache:/usr/local/bundle/gems
    networks:
      - mars-images-network
  