version: "3.3"

volumes:
  redis-data: null
  postgres-data: null

networks:
  rover-map:

services:
  redis:
    image: redis
    command: redis-server --requirepass password
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/data"
    networks:
      - rover-map

  postgresql:
    image: "postgres:10"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    networks:
      - rover-map
