version: "3.3"

volumes:
  redis-data: null
  postgres-data: null
  gem_cache: null

networks:
  mars-images-network:

services:
  redis:
    image: redis
    command: redis-server --requirepass password
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/data"
    networks:
      - mars-images-network

  postgresql:
    image: "postgres:10"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    networks:
      - mars-images-network

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - postgresql
      - redis
    volumes:
      - ./:/opt/app
      - gem_cache:/usr/local/bundle/gems
    networks:
      - mars-images-network
